-- Insert countries with 3-letter country codes and emoji flags
INSERT INTO countries (uuid, full_name, country_code, continent_id, flag)
VALUES (gen_random_uuid(), 'Algeria', 'DZA', 3, '🇩🇿'),
       (gen_random_uuid(), 'Argentina', 'ARG', 5, '🇦🇷'),
       (gen_random_uuid(), 'Australia', 'AUS', 6, '🇦🇺'),
       (gen_random_uuid(), 'Austria', 'AUT', 1, '🇦🇹'),
       (gen_random_uuid(), 'Belgium', 'BEL', 1, '🇧🇪'),
       (gen_random_uuid(), 'Brazil', 'BRA', 5, '🇧🇷'),
       (gen_random_uuid(), 'Cameroon', 'CMR', 3, '🇨🇲'),
       (gen_random_uuid(), 'Canada', 'CAN', 4, '🇨🇦'),
       (gen_random_uuid(), 'Chile', 'CHL', 5, '🇨🇱'),
       (gen_random_uuid(), 'China', 'CHN', 2, '🇨🇳'),
       (gen_random_uuid(), 'Colombia', 'COL', 5, '🇨🇴'),
       (gen_random_uuid(), 'Denmark', 'DNK', 1, '🇩🇰'),
       (gen_random_uuid(), 'Egypt', 'EGY', 3, '🇪🇬'),
       (gen_random_uuid(), 'England', 'GBR', 1, '🏴󠁧󠁢󠁥󠁮󠁧󠁿'),
       (gen_random_uuid(), 'Finland', 'FIN', 1, '🇫🇮'),
       (gen_random_uuid(), 'France', 'FRA', 1, '🇫🇷'),
       (gen_random_uuid(), 'Ghana', 'GHA', 3, '🇬🇭'),
       (gen_random_uuid(), 'Germany', 'DEU', 1, '🇩🇪'),
       (gen_random_uuid(), 'Hungary', 'HUN', 1, '🇭🇺'),
       (gen_random_uuid(), 'Iceland', 'ISL', 1, '🇮🇸'),
       (gen_random_uuid(), 'India', 'IND', 2, '🇮🇳'),
       (gen_random_uuid(), 'Iran', 'IRN', 2, '🇮🇷'),
       (gen_random_uuid(), 'Ireland', 'IRL', 1, '🇮🇪'),
       (gen_random_uuid(), 'Italy', 'ITA', 1, '🇮🇹'),
       (gen_random_uuid(), 'Ivory Coast', 'CIV', 3, '🇨🇮'),
       (gen_random_uuid(), 'Japan', 'JPN', 2, '🇯🇵'),
       (gen_random_uuid(), 'Kenya', 'KEN', 3, '🇰🇪'),
       (gen_random_uuid(), 'Mexico', 'MEX', 4, '🇲🇽'),
       (gen_random_uuid(), 'Morocco', 'MAR', 3, '🇲🇦'),
       (gen_random_uuid(), 'Netherlands', 'NLD', 1, '🇳🇱'),
       (gen_random_uuid(), 'New Zealand', 'NZL', 6, '🇳🇿'),
       (gen_random_uuid(), 'Nigeria', 'NGA', 3, '🇳🇬'),
       (gen_random_uuid(), 'Norway', 'NOR', 1, '🇳🇴'),
       (gen_random_uuid(), 'Peru', 'PER', 5, '🇵🇪'),
       (gen_random_uuid(), 'Portugal', 'PRT', 1, '🇵🇹'),
       (gen_random_uuid(), 'Qatar', 'QAT', 2, '🇶🇦'),
       (gen_random_uuid(), 'Romania', 'ROU', 1, '🇷🇴'),
       (gen_random_uuid(), 'Russia', 'RUS', 2, '🇷🇺'),
       (gen_random_uuid(), 'Saudi Arabia', 'SAU', 2, '🇸🇦'),
       (gen_random_uuid(), 'Scotland', 'GBR', 1, '🏴󠁧󠁢󠁳󠁣󠁴󠁿'),
       (gen_random_uuid(), 'Senegal', 'SEN', 3, '🇸🇳'),
       (gen_random_uuid(), 'South Africa', 'ZAF', 3, '🇿🇦'),
       (gen_random_uuid(), 'South Korea', 'KOR', 2, '🇰🇷'),
       (gen_random_uuid(), 'Spain', 'ESP', 1, '🇪🇸'),
       (gen_random_uuid(), 'Sweden', 'SWE', 1, '🇸🇪'),
       (gen_random_uuid(), 'Switzerland', 'CHE', 1, '🇨🇭'),
       (gen_random_uuid(), 'Taiwan', 'TWN', 2, '🇹🇼'),
       (gen_random_uuid(), 'Turkey', 'TUR', 1, '🇹🇷'),
       (gen_random_uuid(), 'Ukraine', 'UKR', 1, '🇺🇦'),
       (gen_random_uuid(), 'United States', 'USA', 4, '🇺🇸'),
       (gen_random_uuid(), 'Uruguay', 'URY', 5, '🇺🇾'),
       (gen_random_uuid(), 'Venezuela', 'VEN', 5, '🇻🇪'),
       (gen_random_uuid(), 'Wales', 'GBR', 1, '🏴󠁧󠁢󠁷󠁬󠁳󠁿'),
       (gen_random_uuid(), 'Zimbabwe', 'ZWE', 3, '🇿🇼');